In [2]:
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4 5]


In [4]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a, b)
toc = time.time()

print(str(1000* (toc-tic)))

1.0118484497070312


In [7]:
c = 0
tic = time.time()

for i in range(1000000):
    c += a[i] * b[i]

toc = time.time()

print(str(1000* (toc-tic)))

548.9637851715088


In [9]:
A = np.array([
    [56.0, 0, 4.4 ,68],
    [1.2, 104, 52, 8],
    [1.8, 135, 99, 0.9]
])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [11]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [13]:
per = 100*A / cal.reshape(1, 4)
print(per)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [19]:
cal.reshape(1, 4)

array([[ 59. , 239. , 155.4,  76.9]])